### ISSUE TITLE
Compliance Matrix Validation for rel1.0.0 -Span

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#717]
This ticket is to validate the below attributes of Spec Compliance Matrix for Rel 1.0.0. While validation, if there is any ticket created for non-compliance, mention that next to the non-compliant point below in the description.

Link: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/spec-compliance-matrix.md#traces

Span:
* [x] Create root span.
* [x] Create with default parent (active span)
* [ ] Create with parent from Context   -> ( supports parent from SpanContext )
* [ ] No explicit parent Span/SpanContext allowed -> ( support explicit parent SpanContext )
* [ ] SpanProcessor.OnStart receives parent Context   -> ( receives parent SpanConext )
* [x] UpdateName
* [x] User-defined start timestamp
* [x] End
* [x] End with timestamp
* [x] IsRecording
* [x] IsRecording becomes false after End
* [x] Set status with StatusCode (Unset, Ok, Error
* [x] Safe for concurrent calls
* [ ] events collection size limit #365 
* [ ] attribute collection size limit #365 
* [ ] links collection size limit  #365 

Span Attributes:
* [x] SetAttribute
* [x] Set order preserved
* [x] String type
* [x] Boolean type
* [x] Double floating-point type
* [x] Signed int64 type   -> (reserved for future support - uint32, int32, uint64 )
* [x] Array of primitives (homogeneous)  -> (reserved for future support - uint32[], int32[], uint64[]. uint8[] )
* [x] null values documented as invalid/undefined
* [x] Unicode support for keys and string values -> ( using `nostd::string_view`)

Span Linking:
* [x] Add Links
* [x] Safe for concurrent calls

Span Events:
* [x] Add Events
* [x] Add order preserved
* [x] Safe for concurrent calls

Span Exceptions:
* [ ] RecordException (#760)
* [ ] RecordException with extra parameters (#760)

Sampling:
* [x] Allow samplers to modify tracestate
* [x] ShouldSample gets full parent Context

Others:
* [x] New Span ID created also for non-recording Spans
* [x] Id Generators
* [ ]  Span Limits ( Optional ) (#365)

**Comment by lalitb** [comment]
### [Span ](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/specification/trace/api.md#span)

>  **Create with default parent (active span)**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/tracer.cc#L25-L26

>  **Create with parent from Context**

This needs clarification as the API expects parent SpanContext, and not the Context object,

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L69-L73

>  **No explicit parent Span/SpanContext allowed**

This needs clarification as the API expects parent SpanContext, and not the full parent Context,
https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/trace/span.h#L64

>  **SpanProcessor.OnStart receives parent Context**

This needs clarification as it receives parent span_context:

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L106

>  **UpdateName**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L164

> **User-defined start timestamp**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L103

> **End**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L174

> **End with timestamp**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/trace/span.h#L75-L79
https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L174

> **IsRecording**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L197

> ** IsRecording becomes false after End**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L194


> **Set status with StatusCode (Unset, Ok, Error**
https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/trace/span.h#L35-40

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L154

**Comment by lalitb** [comment]
### [Span Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/specification/trace/api.md#set-attributes)

> **SetAttribute**

   Attributes can be set as part of Span constructor, and through Span::SetAttribute() method:
https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.h#L31-L32

> **Set order preserved**

attributes are passed to the exporter in the same order as set through Span::SetAttribute() function.

> **String type**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/common/attribute_value.h#L46

> **Boolean type**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/common/attribute_value.h#L35

> **Double floating-point type**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/common/attribute_value.h#L39

> **Signed int64 type**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/common/attribute_value.h#L36-L38
https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/common/attribute_value.h#L49

(support for uint32, int32, uint64, int64).

> **Array of primitives (homogeneous)**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/common/attribute_value.h#L41-L46
https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/common/attribute_value.h#L52
https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/api/include/opentelemetry/common/attribute_value.h#L55

> **null values documented as invalid/undefined**

null values are not possible

> **Unicode support for keys and string values**

Both key and value are passed as `nostd::string_view`, and it is possible to pass the unicode (UTF-8) character streams through it. Thoght it won't be possible to find the size of unicode string, or also not possible to work at code-point level. Exorter need to read the sequence of characters, and handle them accordingly.

**Comment by lalitb** [comment]
### [Span Linking](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/specification/trace/api.md#specifying-links)

> Add Links

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L96-L100




> Safe for concurrent calls

Links are added as part of span creating, so it is safe for concurrent call

**Comment by lalitb** [comment]
### [Span Events](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#add-events)

 > **Add Events**



https://github.com/open-telemetry/opentelemetry-cpp/blob/v0.6.0/sdk/src/trace/span.cc#L142


> **Add order preserved**

`sdk::trace::SpanData` preservers order by storing Events in std::vector:
https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/include/opentelemetry/sdk/trace/span_data.h#L262

Each exporter handles order separately.

>  **Safe for concurrent calls**

mutex guard.

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/span.cc#L142-L146

**Comment by lalitb** [comment]
### [Record Exception](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#record-exception)

Not Supported ( #760 )

**Comment by lalitb** [comment]
### [Sampling](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampling):

> **Allow samplers to modify tracestate**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/include/opentelemetry/sdk/trace/sampler.h#L40-L47


> **ShouldSample gets full parent Context**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/include/opentelemetry/sdk/trace/sampler.h#L72-L74

**Comment by lalitb** [comment]
### Others

> **New Span ID created also for non-recording Spans**

https://github.com/open-telemetry/opentelemetry-cpp/blob/b4584adeaae259df89b33af884c641e70a60a7cf/sdk/src/trace/tracer.cc#L30-L37

> **Id Generators**

https://github.com/open-telemetry/opentelemetry-cpp/blob/v0.6.0/sdk/include/opentelemetry/sdk/trace/id_generator.h


> **Span Limits ( Optional )**

Not planned. #365

**Comment by lalitb** [comment]
Closing, as validation complete and created required tickets.
