### ISSUE TITLE
Beta readiness tracker

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-cpp#80]
This is a tracking issue for the requirements outlined in the beta release document: https://docs.google.com/document/d/1eviggoIguOS89dgKL-8ntUOCfPP6FLWAoQkGoBDsld0/edit#

## Traces
* [x]  Stable API of every spec'd feature
* [ ]  SDK Implementation of every spec'd feature
    * [x]  Basic tracing
    * [ ]  Named tracers
    * [x]  Tracers use OTEP 66 Context mechanism - This is an implementation detail and does not affect the API

## Resources
* [x]  Stable API of every spec'd feature
* [ ]  SDK Implementation of every spec'd feature

## Context Propagation
* [x]  Stable API of every spec'd feature
   * [x]  Basic context mechanism
   * [ ]  Global Propagators API
   * [ ]  Global Context API (get and set active context)
* [x]  SDK Implementation of every spec'd feature
   * [x]  Basic context mechanism
   * [ ]  Global Propagators

## Exporters
* [x]  OpenTelemetry Native - Collector Exporter
* [x]  Prometheus
* [ ]  Jaeger ( stretch goal)
* [x]  Zipkin

## Examples
* [x]  Manual tracing hello world example
* [x]  HTTP client/server using an instrumented framework
* [ ]  gRPC client/server
